apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: fintech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service:latest
        imagePullPolicy: Never  # Usar imagem local
        ports:
        - containerPort: 80
        command: ["dotnet"]
        args: ["aspnetapp.dll", "--urls", "http://0.0.0.0:5198"]
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:5198"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 5198
          initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: fintech
spec:
  selector:
    app: account-service
  ports:
  - port: 5198
    targetPort: 5198
