apiVersion: v1
kind: Secret
metadata:
  name: fintech-secrets
  namespace: fintech
type: Opaque
data:
  sa-password: WW91clN0cm9uZ0BQYXNzdzByZA==
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXktZm9yLXRlc3Rpbmc=
